# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SuperadminDeleteAdmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SuperadminDeleteAdmin(object):
    def setupUi(self, SuperadminDeleteAdmin):
        SuperadminDeleteAdmin.setObjectName("SuperadminDeleteAdmin")
        SuperadminDeleteAdmin.resize(490, 413)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SuperadminDeleteAdmin)
        self.horizontalLayout.setContentsMargins(-1, 35, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TitleLabel = TitleLabel(SuperadminDeleteAdmin)
        self.TitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout_2.addWidget(self.TitleLabel)
        self.CardWidget = CardWidget(SuperadminDeleteAdmin)
        self.CardWidget.setObjectName("CardWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.CardWidget)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.CardWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.adminId = LineEdit(self.CardWidget)
        self.adminId.setObjectName("adminId")
        self.verticalLayout_8.addWidget(self.adminId)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.finshButton = PrimaryPushButton(self.CardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finshButton.sizePolicy().hasHeightForWidth())
        self.finshButton.setSizePolicy(sizePolicy)
        self.finshButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.finshButton.setObjectName("finshButton")
        self.horizontalLayout_7.addWidget(self.finshButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addWidget(self.CardWidget)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(SuperadminDeleteAdmin)
        QtCore.QMetaObject.connectSlotsByName(SuperadminDeleteAdmin)

    def retranslateUi(self, SuperadminDeleteAdmin):
        _translate = QtCore.QCoreApplication.translate
        SuperadminDeleteAdmin.setWindowTitle(_translate("SuperadminDeleteAdmin", "删除管理员"))
        self.TitleLabel.setText(_translate("SuperadminDeleteAdmin", "删除管理员"))
        self.label_11.setText(_translate("SuperadminDeleteAdmin", "管理员工号："))
        self.finshButton.setText(_translate("SuperadminDeleteAdmin", "完成"))
from qfluentwidgets import CardWidget, LineEdit, PrimaryPushButton, TitleLabel
