# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminSearchReader.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminSearchReader(object):
    def setupUi(self, AdminSearchReader):
        AdminSearchReader.setObjectName("AdminSearchReader")
        AdminSearchReader.resize(672, 490)
        self.horizontalLayout = QtWidgets.QHBoxLayout(AdminSearchReader)
        self.horizontalLayout.setContentsMargins(-1, 35, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TitleLabel = TitleLabel(AdminSearchReader)
        self.TitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout_2.addWidget(self.TitleLabel)
        self.CardWidget = CardWidget(AdminSearchReader)
        self.CardWidget.setObjectName("CardWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.CardWidget)
        self.verticalLayout.setContentsMargins(15, 15, 15, 15)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.readerList = TableWidget(self.CardWidget)
        self.readerList.setObjectName("readerList")
        self.readerList.setColumnCount(5)
        self.readerList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.readerList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.readerList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.readerList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.readerList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.readerList.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.readerList)
        self.verticalLayout_2.addWidget(self.CardWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(AdminSearchReader)
        QtCore.QMetaObject.connectSlotsByName(AdminSearchReader)

    def retranslateUi(self, AdminSearchReader):
        _translate = QtCore.QCoreApplication.translate
        AdminSearchReader.setWindowTitle(_translate("AdminSearchReader", "查看读者信息"))
        self.TitleLabel.setText(_translate("AdminSearchReader", "查看读者信息"))
        item = self.readerList.horizontalHeaderItem(0)
        item.setText(_translate("AdminSearchReader", "账号"))
        item = self.readerList.horizontalHeaderItem(1)
        item.setText(_translate("AdminSearchReader", "密码"))
        item = self.readerList.horizontalHeaderItem(2)
        item.setText(_translate("AdminSearchReader", "姓名"))
        item = self.readerList.horizontalHeaderItem(3)
        item.setText(_translate("AdminSearchReader", "学号"))
        item = self.readerList.horizontalHeaderItem(4)
        item.setText(_translate("AdminSearchReader", "部门"))
from qfluentwidgets import CardWidget, TableWidget, TitleLabel
